-- Ejecutar despues de que Spring Boot haya creado las tablas por primera vez.
BEGIN;
CREATE TABLE IF NOT EXISTS auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    usuario_bd TEXT NOT NULL DEFAULT session_user,
    usuario_app TEXT,
    operacion TEXT NOT NULL CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE')),
    esquema TEXT NOT NULL,
    tabla TEXT NOT NULL,
    registro_id TEXT,
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    cliente_ip INET DEFAULT inet_client_addr(),
    transaccion_id BIGINT NOT NULL DEFAULT txid_current()
);

CREATE OR REPLACE FUNCTION trailersys_registrar_auditoria() RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
DECLARE anterior JSONB; nuevo JSONB;
BEGIN
    -- Los jobs automaticos (ej. ViajeSimulacionService, cada 60s) hacen su
    -- propio SET LOCAL trailersys.omitir_auditoria='true' antes de escribir:
    -- sin esto, cada tick del scheduler quedaba auditado como si fuera una
    -- accion de un usuario, y en la practica eso termino siendo la mayor
    -- parte del volumen de la bitacora (ver 12_auditoria_omitir_automatico.sql).
    -- Es SET LOCAL (no SET), asi que solo aplica dentro de esa transaccion
    -- puntual - nunca a otras conexiones ni a la escritura manual de un
    -- usuario real, aunque comparta el mismo metodo de servicio.
    IF current_setting('trailersys.omitir_auditoria', true) = 'true' THEN
        IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
        RETURN NEW;
    END IF;

    anterior := CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) END;
    nuevo := CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) END;
    -- to_jsonb(OLD)/to_jsonb(NEW) vuelca la fila ENTERA sin distinguir
    -- columnas sensibles: para "usuarios" eso incluia password_hash (el
    -- bcrypt, no la contraseña en claro, pero sigue siendo un secreto que
    -- no pertenece a una bitacora que cualquier Administrador puede
    -- consultar/exportar). Se quita antes de insertar, no despues.
    IF TG_TABLE_NAME = 'usuarios' THEN
        anterior := anterior - 'password_hash';
        nuevo := nuevo - 'password_hash';
    END IF;
    INSERT INTO public.auditoria (usuario_bd, usuario_app, operacion, esquema, tabla,
        registro_id, datos_anteriores, datos_nuevos)
    VALUES (session_user, NULLIF(current_setting('trailersys.usuario', true), ''),
        TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME,
        COALESCE(nuevo ->> 'id', anterior ->> 'id'), anterior, nuevo);
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END $$;

DO $$
DECLARE nombre_tabla TEXT;
BEGIN
    FOREACH nombre_tabla IN ARRAY ARRAY['usuarios','vehiculos','conductores','clientes',
        'cargas','viajes','seguimiento_eventos','mantenimientos'] LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_auditar ON %I', nombre_tabla);
        EXECUTE format('CREATE TRIGGER trg_auditar AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION trailersys_registrar_auditoria()', nombre_tabla);
    END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_viajes_vehiculo ON viajes (vehiculo_id);
CREATE INDEX IF NOT EXISTS idx_viajes_conductor ON viajes (conductor_id);
CREATE INDEX IF NOT EXISTS idx_viajes_carga ON viajes (carga_id);
CREATE INDEX IF NOT EXISTS idx_viajes_estado_fecha ON viajes (estado, fecha_salida DESC);
CREATE INDEX IF NOT EXISTS idx_seguimiento_viaje_fecha ON seguimiento_eventos (viaje_id, fecha_hora DESC);
CREATE INDEX IF NOT EXISTS idx_mantenimientos_vehiculo_fecha ON mantenimientos (vehiculo_id, fecha DESC);
CREATE INDEX IF NOT EXISTS idx_auditoria_tabla_fecha ON auditoria (tabla, fecha_hora DESC);
CREATE INDEX IF NOT EXISTS idx_auditoria_usuario_fecha ON auditoria (usuario_app, fecha_hora DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_username_upper ON usuarios (upper(username));
CREATE UNIQUE INDEX IF NOT EXISTS uq_vehiculos_placa_upper ON vehiculos (upper(placa));
CREATE UNIQUE INDEX IF NOT EXISTS uq_conductores_identificacion_upper ON conductores (upper(identificacion));
CREATE UNIQUE INDEX IF NOT EXISTS uq_clientes_identificacion_upper ON clientes (upper(identificacion));
COMMIT;
